adjective1 = input("Please enter an adjective ")
adjective2 = input("Please enter an adjective ")
adjective3 = input("Please enter an adjective ")
noun1 = input("Please enter a noun ")
noun2 = input("Please enter a noun ")
noun3 = input("Please enter a noun ")
noun4 = input("Please enter a noun ")
noun5 = input("Please enter a noun ")
noun6 = input("Please enter a noun ")
pluralNoun1 = input("Please enter a plural noun ")
pluralNoun2 = input("Please enter a plural noun ")
pluralNoun3 = input("Please enter a plural noun ")
pluralNoun4 = input("Please enter a plural noun ")
verb1 = input("Please enter a verb ending with ing ")
verb2 = input("Please enter a verb ending with ing ")
verb3 = input("Please enter a verb ending with ing ")
verb4 = input("Please enter a verb ending with ing ")
number = input("Please enter a number ")
game = input("Please enter a game ")

print("A vacation is when you take a trip to some (adjective) play with your (adjective) family.")
print("Usually you go to some place that is near a/an (noun) or up on a/an (noun).")
print("A good vacation place is one  where you can ride (plural noun) or play (game) or go hunting for (plural noun).")
print("I like to spend my time (verb-ing) or (verb-ing).")
print("When parents go on a vacation, they spend their time eating three (plural noun) a day, " +
      "and fathers play golf, and mothers sit around (verb -ing)")
print("Last summer, my little brother fell in a/an (noun) and got poision (plant) all over his (body part).")
print("My family is going to go to (a place), and I will practice (verb-ing).")
print("Parents need vacations more than kids because parents are always very (adjective) " +
      "and because they have to work (number) hours every day all year making enough (plural noun) to par for the vacation.")